---
abstract: "Extract your distribution's Pod::Weaver configuration"
author:
  - 'Florian Ragwitz <rafl@debian.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300029, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-App-Command-weaverconf
provides:
  Dist::Zilla::App::Command::weaverconf:
    file: lib/Dist/Zilla/App/Command/weaverconf.pm
    version: 0.02
requires:
  Data::Visitor: 0
  Dist::Zilla::App: 0
  JSON::Any: 0
  List::AllUtils: 0
  Moose: 0.91
  Moose::Autobox: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Structured: 0.20
  aliased: 0
  namespace::autoclean: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-App-Command-weaverconf
  homepage: https://github.com/karenetheridge/dist-zilla-app-command-weaverconf
  repository: https://github.com/karenetheridge/dist-zilla-app-command-weaverconf.git
version: 0.02
x_Dist_Zilla:
  perl:
    version: 5.016002
  plugins:
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@FLORA/@Basic/GatherDir'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@FLORA/@Basic/PruneCruft'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@FLORA/@Basic/ManifestSkip'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@FLORA/@Basic/MetaYAML'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::License
      name: '@FLORA/@Basic/License'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@FLORA/@Basic/Readme'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@FLORA/@Basic/ExtraTests'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@FLORA/@Basic/ExecDir'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@FLORA/@Basic/ShareDir'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MakeMaker
      name: '@FLORA/@Basic/MakeMaker'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@FLORA/@Basic/Manifest'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@FLORA/@Basic/TestRelease'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@FLORA/@Basic/ConfirmRelease'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@FLORA/@Basic/UploadToCPAN'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@FLORA/MetaConfig'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@FLORA/MetaJSON'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@FLORA/PkgVersion'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@FLORA/PodSyntaxTests'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      name: '@FLORA/NoTabsTests'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: '@FLORA/MetaResources'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@FLORA/Authority'
      version: 1.006
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@FLORA/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@FLORA/PodWeaver'
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@FLORA/AutoPrereqs'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: Test::Compile
      version: 1.112820
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: NextRelease
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: GithubMeta
      version: 0.28
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: Git::Describe
      version: 0.002
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: InstallGuide
      version: 1.200000
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: MetaConfig
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: MetaProvides::Package
      version: 1.14000001
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: MinimumPerl
      version: 1.003
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: Git::Remote::Check
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: Git::CheckFor::CorrectBranch
      version: 0.006
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: Git::Check
      version: 2.006
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: Git::Commit
      version: 2.006
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: Git::Tag
      version: 2.006
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: Git::Push
      version: 2.006
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: InstallRelease
      version: 0.008
    -
      class: Dist::Zilla::Plugin::Clean
      name: Clean
      version: 0.07
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300029
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300029
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.300029
x_authority: cpan:FLORA
